services:
  # 1. OpenConnect Client (The exit point)
  openconnect:
    image: ghcr.io/di0ik/openconnect-vpn:main
    build:
      context: .
      network: host
    container_name: openconnect-vpn
    # Critical security settings for VPN
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    devices:
      - /dev/net/tun
    privileged: true
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - vpn_net

  # 2. WireGuard Client (Traffic is routed through OpenConnect's network)
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard-client
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./wireguard/wg0.conf:/config/wg0.conf
    network_mode: service:openconnect
    restart: unless-stopped

networks:
  vpn_net:
    driver: bridge
